---
name: CI
on: push

env:
  PROJECT: bash-ssh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build local container for scanning
        uses: docker/build-push-action@v3
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true
      - name: Scan image
        run: |
          docker run --rm \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --name Grype anchore/grype:latest \
            localbuild/testimage:latest \
            --output sarif --fail-on medium --add-cpes-if-none --distro alpine:3.16.3 | tee ./results.sarif
      - name: Remove test image
        run: docker image rm localbuild/testimage --force
      - name: Upload scan report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./results.sarif
      - name: Inspect scan report
        run: cat ./results.sarif
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Buildx
        shell: bash
        run: |
          docker buildx build . -f Dockerfile \
            --squash \
            --tag alpine-bash-curl-jq-yq:local \
            --output=type=docker \
            --progress plain
      - name: Push to DockerHub
        run: |
          docker tag alpine-bash-curl-jq-yq:local jakobjs/bash-ssh:latest
          docker push jakobjs/bash-ssh:latest
